
############################################################
#                       General                            #
############################################################
metasheet: metasheet.csv
ref: ref.yaml
assembly: hg38
#Options are [ACC, BLCA, BRCA, CESC, CHOL, COAD, DLBC, ESCA, GBM, HNSC, KICH, KIRC, KIRP, LGG, LIHC, LUAD, LUSC, MESO, OV, PAAD, PCPG, PRAD, READ, SARC, SKCM, STAD, TGCT, THCA, THYM, UCEC, UCS, UVM]
cancer_type: LUAD


#########User defined parameters needed to run the modules################
#------- preprocess  module--------#
#Possible values are [ff-firststrand, ff-secondstrand, ff-unstranded, fr-firststrand, fr-secondstrand, fr-unstranded (default), transfrags]
library_type: 'fr-firststrand'
stranded: true
rseqc_ref: house_keeping  #rseqc ref model
mate: [1,2] #paired-end([1,2]) or single-end([0])

############################################################
#                     list samples                         #
############################################################

samples:
  SAMPLE1:
      - data/SAMPLE1_1.fq
      - data/SAMPLE1_2.fq



############################################################
#                       run settings                       #
############################################################
#runs:
#  run_SAMPLE1:
#   - SAMPLE1
